services:
  - type: web
    name: speech-practice-platform
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1